import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  site: 'https://drychillis.com',
  output: 'static',
  build: { format: 'directory' },
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'es', 'ar'],
    routing: {
      prefixDefaultLocale: false,
      redirectToDefaultLocale: false,
    },
  },
  redirects: {
    '/products/paprika/': '/products/paprika-powder/',
    '/products/paprika': '/products/paprika-powder/',
    '/quality/': '/quality-certifications/',
    '/quality': '/quality-certifications/',
    '/about/': '/about-us/',
    '/about': '/about-us/',
    '/terms-and-conditions/': '/terms/',
    '/terms-and-conditions': '/terms/',
    '/blog/': '/guides/',
    '/blog': '/guides/',
    '/blog/how-to-specify-chilli-powder/': '/guides/paprika-chilli-buying-guide/',
    '/blog/how-to-specify-chilli-powder': '/guides/paprika-chilli-buying-guide/',
    '/blog/chilli-heat-shu-explained/': '/guides/asta-colour-and-shu-heat-explained/',
    '/blog/chilli-heat-shu-explained': '/guides/asta-colour-and-shu-heat-explained/',
    '/blog/chinese-chilli-varieties-guide/': '/guides/chinese-chilli-varieties-grades/',
    '/blog/chinese-chilli-varieties-guide': '/guides/chinese-chilli-varieties-grades/',
    '/varieties/sanying/': '/products/sanying-chilli/',
    '/varieties/sanying': '/products/sanying-chilli/',
    '/es/products/paprika/': '/es/products/paprika-powder/',
    '/es/products/paprika': '/es/products/paprika-powder/',
    '/es/quality/': '/es/quality-certifications/',
    '/es/quality': '/es/quality-certifications/',
    '/es/about/': '/es/about-us/',
    '/es/about': '/es/about-us/',
    '/es/terms-and-conditions/': '/es/terms/',
    '/es/terms-and-conditions': '/es/terms/',
    '/es/blog/': '/es/guides/',
    '/es/blog': '/es/guides/',
    '/es/blog/how-to-specify-chilli-powder/': '/es/guides/paprika-chilli-buying-guide/',
    '/es/blog/how-to-specify-chilli-powder': '/es/guides/paprika-chilli-buying-guide/',
    '/es/blog/chilli-heat-shu-explained/': '/es/guides/asta-colour-and-shu-heat-explained/',
    '/es/blog/chilli-heat-shu-explained': '/es/guides/asta-colour-and-shu-heat-explained/',
    '/es/blog/chinese-chilli-varieties-guide/': '/es/guides/chinese-chilli-varieties-grades/',
    '/es/blog/chinese-chilli-varieties-guide': '/es/guides/chinese-chilli-varieties-grades/',
    '/es/varieties/sanying/': '/es/products/sanying-chilli/',
    '/es/varieties/sanying': '/es/products/sanying-chilli/',
    '/ar/products/paprika/': '/ar/products/paprika-powder/',
    '/ar/products/paprika': '/ar/products/paprika-powder/',
    '/ar/quality/': '/ar/quality-certifications/',
    '/ar/quality': '/ar/quality-certifications/',
    '/ar/about/': '/ar/about-us/',
    '/ar/about': '/ar/about-us/',
    '/ar/terms-and-conditions/': '/ar/terms/',
    '/ar/terms-and-conditions': '/ar/terms/',
    '/ar/blog/': '/ar/guides/',
    '/ar/blog': '/ar/guides/',
    '/ar/blog/how-to-specify-chilli-powder/': '/ar/guides/paprika-chilli-buying-guide/',
    '/ar/blog/how-to-specify-chilli-powder': '/ar/guides/paprika-chilli-buying-guide/',
    '/ar/blog/chilli-heat-shu-explained/': '/ar/guides/asta-colour-and-shu-heat-explained/',
    '/ar/blog/chilli-heat-shu-explained': '/ar/guides/asta-colour-and-shu-heat-explained/',
    '/ar/blog/chinese-chilli-varieties-guide/': '/ar/guides/chinese-chilli-varieties-grades/',
    '/ar/blog/chinese-chilli-varieties-guide': '/ar/guides/chinese-chilli-varieties-grades/',
    '/ar/varieties/sanying/': '/ar/products/sanying-chilli/',
    '/ar/varieties/sanying': '/ar/products/sanying-chilli/',
  },
  integrations: [sitemap()],
});
